# Define variables (you can change these later)
CC = g++
CFLAGS = -Wall -std=c++11
SRC = main.cpp
OBJ = main.o
TARGET = my_program

# Default rule (executed when running 'make')
all:
	@echo "Makefile is set up! Add compilation rules here."

# Clean rule to remove compiled files
clean:
	rm -f $(OBJ) $(TARGET)
